### PR TITLE
Added `skip_cleanup: true`

### PR DESCRIPTION
**Pull request by cotsog**
in order to not revert the changes before the deployment.

### CODE REVIEW

**Comment by agronholm** [comment]
Could you elaborate a bit more on this? Why is `skip_cleanup` needed here?

**Comment by cotsog** [comment]
@agronholm: Sorry for the lack of details. `skip_cleanup: true` will prevent Travis CI from reverting any change made to your repo during your build. This is often needed when the is a generated artifact to upload. I'm not sure if it's the case here, however, I wanted to see if your issue was caused by our attempt to revert the changes. Mostly because of the following error message I see in the deployment steps:

```
/usr/lib/git-core/git-stash: 186: /usr/lib/git-core/git-stash: cannot create /home/travis/build/agronholm/typeguard/.git/logs/refs/stash: Directory nonexistent
```

**Comment by agronholm** [comment]
The `sdist` and `bdist_wheel` commands don't rely on any build artifacts so `skip_cleanup` is irrelevant here.

**Comment by agronholm** [comment]
There were a bunch of other issues in my report that cannot possibly be caused by this setting anyway. Can you confirm that PyPI deploy is at least working for someone? I've heard reports of projects abandoning Travis based PyPI deploys.

**Comment by agronholm** [comment]
Any progress in the investigation? I'd like to help as much as I can. Do you feel that `skip_cleanup` could have an effect despite what I said ealier?

**Comment by cotsog** [comment]
Hey @agronholm,

Sorry for the delay of my reply.

We haven't have other reports of failed PyPI deployment so it's hard for us to tell if the issue is systematic.

I think the `skip_cleanup` option is worth a try.

Please let me know the result if/when you try it.

Thanks!

**Comment by agronholm** [comment]
At least this project had difficulties: https://github.com/internap/python-ubersmith-remote-module-server/commit/77d36bd15d4fe3af1771a59ccdd600c7cd0eec14

**Comment by agronholm** [comment]
Well, I pushed a tagged commit and Travis says:

> Skipping a deployment with the pypi provider because this is not a tagged commit

So what am I supposed to do to get Travis to deploy? Even the email I got from Travis has the tag in the subject!

**Pull request merged**
