### PR TITLE
Support Python 3.13

### PR DESCRIPTION
**Pull request by JelleZijlstra**
- typing.is_typeddict() does not recognize typing_extensions.TypedDict
- ForwardRef._evaluate gained another parameter

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
The test failures are due to some pytest deprecation; it's not immediately obvious where the problem is.

**Comment by JelleZijlstra** [comment]
The good news is that my draft PEP 649 implementation (https://github.com/python/cpython/pull/119361) passes the entire test suite, once this change is implied and I ignore the pytest deprecation.

**Comment by agronholm** [comment]
This needs additional tests. If `typing_extensions` is to be imported unconditionally, then the conditional dependency on it in `pyproject.toml` must be made unconditional.

**Comment by JelleZijlstra** [comment]
The test suite already tests for both `typing.TypedDict` and `typing_extensions.TypedDict`; it uses the `typing_provider` fixture to use both. However, I'll add a direct test for `is_typeddict`.

**Comment by agronholm** [comment]
Thanks!!

**Pull request merged**
