### PR TITLE
Fix imports in a module containing __future__

### PR DESCRIPTION
**Pull request by vthemelis**
Fixes: https://github.com/agronholm/typeguard/issues/385

### CODE REVIEW

**Comment by agronholm** [comment]
Are the test suites passing for you locally?

**Comment by vthemelis** [comment]
> Are the test suites passing for you locally?

Yes, I can get a clean run with `tox`. I'm just having trouble with linters being applied to places where they shouldn't by `pre-commit.ci` though which leads to redness on the PR.

**Comment by vthemelis** [comment]
@agronholm All 💚 now!

**Comment by agronholm** [comment]
> Yes, I can get a clean run with `tox`. I'm just having trouble with linters being applied to places where they shouldn't by `pre-commit.ci` though which leads to redness on the PR.

Installing pre-commit locally would have made that easier..

**Comment by agronholm** [comment]
The test for this really belongs in `test_transformer.py`, not in `dummymodule.py`.

**Comment by vthemelis** [comment]
> Installing pre-commit locally would have made that easier..

How do you run it locally? I tried `pre-commit run` but it was no-op for me.

**Comment by vthemelis** [comment]
> The test for this really belongs in `test_transformer.py`, not in `dummymodule.py`.

It seemed like `dummymodule.py` gave me pretty good integration coverage already so I went this way. Do you want me to add unit tests explicitly to `test_transformer.py` too?

**Comment by agronholm** [comment]
First of all, you should do `pre-commit install` which ensures that the checks are run when you do `git commit`. If you want to run the checks without the git hook, do `pre-commit run -a` (`-a` meaning "run for all files").

**Comment by agronholm** [comment]
The problem seems to stem from `__post_init__()` only setting the right injection index if `self.node` is set, which it isn't when a module is being transformed by the import hook.

**Comment by agronholm** [comment]
I'm likely to reject this PR in favor of an alternate approach and an alternate test.

**Comment by agronholm** [comment]
Here's a test that fails without any patch:
```python
def test_respect_future_import() -> None:
    # Regression test for #385
    node = parse(
        dedent(
            '''
            from __future__ import annotations
            
            def foo() -> int:
                return 1
            '''
        )
    )
    TypeguardTransformer().visit(node)
    assert (
        unparse(node)
        == dedent(
            '''
            from __future__ import annotations
            from typeguard import TypeCheckMemo
            from typeguard._functions import check_return_type

            def foo() -> int:
                memo = TypeCheckMemo(globals(), locals())
                return check_return_type('foo', 1, int, memo)
            '''
        ).strip()
    )
```

**Comment by vthemelis** [comment]
> I'm likely to reject this PR in favor of an alternate approach and an alternate test.

Fair enough! Let me know if you want me to help.

**Comment by vthemelis** [comment]
> Here's a test that fails without any patch:

Thanks for this! Seems to pass with my changes. Shall I commit it?

**Comment by agronholm** [comment]
I'm still considering my options. If I figure out a better way, I'll just push that and close this PR. Either way I'll let you know.

**Comment by vthemelis** [comment]
> I'm still considering my options. If I figure out a better way, I'll just push that and close this PR. Either way I'll let you know.

Sounds good. I added the test in case we merge this PR.

**Comment by agronholm** [comment]
Alright, I resolved this via c11057ab9f9570718fe149b2bfa6eef1df6f26a2. Thanks for your initiative on the matter.

**Comment by vthemelis** [comment]
Thanks! Would it be possible to release the latest changes?

**Comment by agronholm** [comment]
> Thanks! Would it be possible to release the latest changes?

Done.

**Pull request closed without merging**
