### PR TITLE
Fill missing type hints

### PR DESCRIPTION
**Pull request by eggplants**
Closes: #240 

`typeguard.typechecking` is too complex to annotate correctly. So please tell me your advice, or annotate it instead of me.

```shellsession
$ mypy src
src/typeguard/__init__.py:1133: error: Function is missing a return type
annotation  [no-untyped-def]
    def typechecked(func=None, *, always=False, _localns: Optional[Dict[st...
    ^
src/typeguard/__init__.py:1133: error: Function is missing a type annotation
for one or more arguments  [no-untyped-def]
    def typechecked(func=None, *, always=False, _localns: Optional[Dict[st...
    ^
src/typeguard/__init__.py:1164: error: No overload variant of "typechecked"
matches argument types "Union[FunctionType, MethodType, Type[Any]]", "Any",
"Dict[str, Any]"  [call-overload]
                            typechecked(attr, always=always, _localns=func...
                            ^
src/typeguard/__init__.py:1164: note: Possible overload variants:
src/typeguard/__init__.py:1164: note:     def typechecked(*, always: bool = ...) -> Callable[[T_CallableOrType], T_CallableOrType]
src/typeguard/__init__.py:1164: note:     def [T_CallableOrType] typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType
src/typeguard/__init__.py:1168: error: No overload variant of "typechecked"
matches argument types "Callable[..., Any]", "Any", "Dict[str, Any]" 
[call-overload]
                        wrapped = typechecked(attr.__func__, always=always...
                                  ^
src/typeguard/__init__.py:1168: note: Possible overload variants:
src/typeguard/__init__.py:1168: note:     def typechecked(*, always: bool = ...) -> Callable[[T_CallableOrType], T_CallableOrType]
src/typeguard/__init__.py:1168: note:     def [T_CallableOrType] typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType
src/typeguard/__init__.py:1174: error: Argument 3 to "getattr" has incompatible
type "Tuple[]"; expected "bool"  [arg-type]
    ...ty_func is not None and getattr(property_func, "__annotations__", ()):
                                                                         ^
src/typeguard/__init__.py:1175: error: No overload variant of "typechecked"
matches argument types "Any", "Any", "Dict[str, Any]"  [call-overload]
                            kwargs[name] = typechecked(
                                           ^
src/typeguard/__init__.py:1175: note: Possible overload variants:
src/typeguard/__init__.py:1175: note:     def typechecked(*, always: bool = ...) -> Callable[[T_CallableOrType], T_CallableOrType]
src/typeguard/__init__.py:1175: note:     def [T_CallableOrType] typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType
src/typeguard/__init__.py:1179: error: Argument 1 to "property" has
incompatible type "**Dict[str, Optional[str]]"; expected
"Optional[Callable[[Any], Any]]"  [arg-type]
                    setattr(func, key, attr.__class__(**kwargs))
                                                        ^
src/typeguard/__init__.py:1179: error: Argument 1 to "property" has
incompatible type "**Dict[str, Optional[str]]"; expected
"Optional[Callable[[Any, Any], None]]"  [arg-type]
                    setattr(func, key, attr.__class__(**kwargs))
                                                        ^
src/typeguard/__init__.py:1179: error: Argument 1 to "property" has
incompatible type "**Dict[str, Optional[str]]"; expected
"Optional[Callable[[Any], None]]"  [arg-type]
                    setattr(func, key, attr.__class__(**kwargs))
                                                        ^
src/typeguard/__init__.py:1219: error: Returning Any from function declared to
return
"Union[TypeCheckedGenerator, TypeCheckedAsyncGenerator, GeneratorType[Any, Any, Any]]"
 [no-any-return]
            return retval
            ^
Found 10 errors in 1 file (checked 3 source files)
```

### CODE REVIEW

**Comment by eggplants** [comment]
@agronholm Have you setup `pre-commit.ci`?

**Comment by eggplants** [comment]
> Why have you added all sorts of unrelated configuration?

Sorry, removed.

**Comment by agronholm** [comment]
> Closes: #240
> 
> `typeguard.typechecking` is too complex to annotate correctly. So please tell me your advice, or annotate it instead of me.
> 
> ```
> $ mypy src
> src/typeguard/__init__.py:1133: error: Function is missing a return type
> annotation  [no-untyped-def]
>     def typechecked(func=None, *, always=False, _localns: Optional[Dict[st...
>     ^
> src/typeguard/__init__.py:1133: error: Function is missing a type annotation
> for one or more arguments  [no-untyped-def]
>     def typechecked(func=None, *, always=False, _localns: Optional[Dict[st...
>     ^
> src/typeguard/__init__.py:1164: error: No overload variant of "typechecked"
> matches argument types "Union[FunctionType, MethodType, Type[Any]]", "Any",
> "Dict[str, Any]"  [call-overload]
>                             typechecked(attr, always=always, _localns=func...
>                             ^
> src/typeguard/__init__.py:1164: note: Possible overload variants:
> src/typeguard/__init__.py:1164: note:     def typechecked(*, always: bool = ...) -> Callable[[T_CallableOrType], T_CallableOrType]
> src/typeguard/__init__.py:1164: note:     def [T_CallableOrType] typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType
> src/typeguard/__init__.py:1168: error: No overload variant of "typechecked"
> matches argument types "Callable[..., Any]", "Any", "Dict[str, Any]" 
> [call-overload]
>                         wrapped = typechecked(attr.__func__, always=always...
>                                   ^
> src/typeguard/__init__.py:1168: note: Possible overload variants:
> src/typeguard/__init__.py:1168: note:     def typechecked(*, always: bool = ...) -> Callable[[T_CallableOrType], T_CallableOrType]
> src/typeguard/__init__.py:1168: note:     def [T_CallableOrType] typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType
> src/typeguard/__init__.py:1174: error: Argument 3 to "getattr" has incompatible
> type "Tuple[]"; expected "bool"  [arg-type]
>     ...ty_func is not None and getattr(property_func, "__annotations__", ()):
>                                                                          ^
> src/typeguard/__init__.py:1175: error: No overload variant of "typechecked"
> matches argument types "Any", "Any", "Dict[str, Any]"  [call-overload]
>                             kwargs[name] = typechecked(
>                                            ^
> src/typeguard/__init__.py:1175: note: Possible overload variants:
> src/typeguard/__init__.py:1175: note:     def typechecked(*, always: bool = ...) -> Callable[[T_CallableOrType], T_CallableOrType]
> src/typeguard/__init__.py:1175: note:     def [T_CallableOrType] typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType
> src/typeguard/__init__.py:1179: error: Argument 1 to "property" has
> incompatible type "**Dict[str, Optional[str]]"; expected
> "Optional[Callable[[Any], Any]]"  [arg-type]
>                     setattr(func, key, attr.__class__(**kwargs))
>                                                         ^
> src/typeguard/__init__.py:1179: error: Argument 1 to "property" has
> incompatible type "**Dict[str, Optional[str]]"; expected
> "Optional[Callable[[Any, Any], None]]"  [arg-type]
>                     setattr(func, key, attr.__class__(**kwargs))
>                                                         ^
> src/typeguard/__init__.py:1179: error: Argument 1 to "property" has
> incompatible type "**Dict[str, Optional[str]]"; expected
> "Optional[Callable[[Any], None]]"  [arg-type]
>                     setattr(func, key, attr.__class__(**kwargs))
>                                                         ^
> src/typeguard/__init__.py:1219: error: Returning Any from function declared to
> return
> "Union[TypeCheckedGenerator, TypeCheckedAsyncGenerator, GeneratorType[Any, Any, Any]]"
>  [no-any-return]
>             return retval
>             ^
> Found 10 errors in 1 file (checked 3 source files)
> ```

You should broaden the annotations, possibly using `Any` where the proper type cannot be determined.

**Comment by agronholm** [comment]
There are code styling changes not related to annotations. Please undo those changes.

The GitHub Actions workflow should have a step to run mypy. You should add that.

**Comment by eggplants** [comment]
@agronholm done.

**Comment by eggplants** [comment]
```shellsession
$ git rev-parse HEAD # now
e84ca55ff3d2743a0924e08ad088f7470f3a4745
$ mypy tests/mypy/test_type_annotations.py src
src/typeguard/__init__.py:1030: error: Argument 3 to "getattr" has incompatible
type "Tuple[]"; expected "bool"
    ...ty_func is not None and getattr(property_func, '__annotations__', ()):
                                                                         ^
src/typeguard/__init__.py:1033: error: Argument 1 to "property" has
incompatible type "**Dict[str, Optional[str]]"; expected
"Optional[Callable[[Any], Any]]"
                    setattr(func, key, attr.__class__(**kwargs))
                                                        ^
src/typeguard/__init__.py:1033: error: Argument 1 to "property" has
incompatible type "**Dict[str, Optional[str]]"; expected
"Optional[Callable[[Any, Any], None]]"
                    setattr(func, key, attr.__class__(**kwargs))
                                                        ^
src/typeguard/__init__.py:1033: error: Argument 1 to "property" has
incompatible type "**Dict[str, Optional[str]]"; expected
"Optional[Callable[[Any], None]]"
                    setattr(func, key, attr.__class__(**kwargs))
                                                        ^
src/typeguard/__init__.py:1057: error: "None" not callable
            retval = func(*args, **kwargs)
                     ^
src/typeguard/__init__.py:1073: error: Returning Any from function declared to
return
"Union[TypeCheckedGenerator, TypeCheckedAsyncGenerator, GeneratorType[Any, Any, Any]]"
            return retval
            ^
src/typeguard/__init__.py:1078: error: "None" not callable
            retval = await func(*args, **kwargs)
                           ^
Found 7 errors in 1 file (checked 4 source files)
```

**Comment by agronholm** [comment]
[This line](https://github.com/agronholm/typeguard/blob/master/.github/workflows/codeqa-test.yml#L26) runs mypy; it should be modified to check the entire codebase.

**Comment by eggplants** [comment]
> [This line](https://github.com/agronholm/typeguard/blob/master/.github/workflows/codeqa-test.yml#L26) runs mypy; it should be modified to check the entire codebase.

See [e84ca55](https://github.com/agronholm/typeguard/pull/241/commits/e84ca55ff3d2743a0924e08ad088f7470f3a4745)

**Comment by agronholm** [comment]
Those mypy errors look nonsensical. I wonder if pyright gives similar errors.

**Comment by agronholm** [comment]
> > [This line](https://github.com/agronholm/typeguard/blob/master/.github/workflows/codeqa-test.yml#L26) runs mypy; it should be modified to check the entire codebase.
> 
> Please check: [e84ca55](https://github.com/agronholm/typeguard/pull/241/commits/e84ca55ff3d2743a0924e08ad088f7470f3a4745)

Ah, quite right.

**Comment by eggplants** [comment]
```shellsession
$ git rev-parse HEAD # now
a9c2fb9c91303e3d75bb121aeba2ae1655e07b99
$ mypy tests/mypy/test_type_annotations.py src
Success: no issues found in 4 source files
$ grep -r '# type: ignore' src/typeguard/*.py | wc -l
20
```

**Comment by agronholm** [comment]
I'm sorry I didn't think of this before (I was travelling), but you probably should've based this on the 3.0 branch. I have no intention of updating the 2.x series anymore.

**Comment by eggplants** [comment]
I have not noticed branch `3.0` until now. I'll try to annotate it later.

**Comment by eggplants** [comment]
> I'm sorry I didn't think of this before (I was travelling), but you probably should've based this on the 3.0 branch. I have no intention of updating the 2.x series anymore.

Please document in either README or Documentation in your free time.

**Comment by agronholm** [comment]
I expected to release 3.0 much sooner but got sidetracked by other work, leading to this awkward situation.

**Comment by eggplants** [comment]
To avoid confusion for others, till 3.0 is published, I recommend either:

- add a single sentence of caution to the README
- pin the Issue that describes this information
- set the Default branch to 3.0
-

**Pull request closed without merging**
