### PR TITLE
Typechecked class properties

### PR DESCRIPTION
**Pull request by EPronovost**
Check `@property`s when `@typechecked` decorates a class.

### CODE REVIEW

**Comment by EPronovost** [comment]
@agronholm I think this is ready to review when you have the time

**Comment by agronholm** [comment]
I haven't forgotten about this. I'll do the review in a few days.

**Comment by agronholm** [comment]
Looks okay to me, but please add a blank line before the next line when a control block ends.

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
